version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: molo_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./app:/var/www/html
      - ./transmission/data/completed:/var/www/html/files
      - ./nginx/init.sh:/init.sh
    networks:
      - molonet
    depends_on:
      - php
    environment:
      - NODE_URL=${NODE_URL}
      - SECRET=${SECRET}
    entrypoint: ["/bin/bash", "/init.sh"]
    expose:
      - "80"

  php:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: molo_php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
      - ./transmission/data/completed:/var/www/html/files:ro
      - ./php/init.sh:/init.sh
    networks:
      - molonet
    environment:
      - NODE_URL=${NODE_URL}
      - SECRET=${SECRET}
    entrypoint: ["/bin/bash", "/init.sh"]

  transmission:
    image: linuxserver/transmission
    container_name: molo_transmission
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000            # Host user ID, adjust to match your file ownership
      - PGID=1000            # Host group ID
      - TZ=Europe/London     # Adjust timezone
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=node
      - TRANSMISSION_RPC_PASSWORD=${SECRET}
      - TRANSMISSION_WATCH_DIR=/data/watch
      - TRANSMISSION_DOWNLOAD_DIR=/data/completed
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_PEER_LIMIT_GLOBAL=405
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=62
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_SPEED_LIMIT_DOWN=125000
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=false
      - TRANSMISSION_SPEED_LIMIT_UP=1000
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_BLOCKLIST_URL=https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz
    volumes:
      - ./transmission/data:/data
      - ./transmission_config:/config
    networks:
      - molonet
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: molo_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - molonet

networks:
  molonet:

volumes:
  caddy_data:
  caddy_config:
